import Link from 'next/link';
import Image from 'next/image';
import { ArrowRight, Braces, Compass, Gauge, Layers3 } from 'lucide-react';
import SectionIntro from '../../components/SectionIntro';
import StudioSystem from '../../components/StudioSystem';
import { whatsappHref } from '../../lib/data';

export const metadata={title:'Sobre',description:'Conheça a Webfun, estúdio digital de Canoinhas que une estratégia, UX/UI, desenvolvimento e performance.',alternates:{canonical:'/sobre'},openGraph:{title:'Sobre | Webfun',description:'Conheça a Webfun, estúdio digital de Canoinhas que une estratégia, UX/UI, desenvolvimento e performance.',url:'/sobre',type:'website',images:[{url:'/opengraph-image',width:1200,height:630,alt:'Webfun | Sobre'}]},twitter:{card:'summary_large_image',title:'Sobre | Webfun',description:'Conheça a Webfun, estúdio digital de Canoinhas que une estratégia, UX/UI, desenvolvimento e performance.',images:['/opengraph-image']}};

const principles=[['Entender primeiro','O projeto começa pelo problema, objetivo e contexto — não pela tela.',Compass],['Design com função','Beleza importa quando ajuda atenção, leitura e decisão.',Layers3],['Tecnologia sem teatro','A stack serve ao produto. Não o contrário.',Braces],['Qualidade de base','Performance, SEO e acessibilidade entram desde o início.',Gauge]];

export default function AboutPage(){return <main id="conteudo" className="v4-internal">
 <section className="v4-page-hero v4-about-hero"><div className="shell v80-page-hero-grid"><div className="v80-page-hero-copy"><SectionIntro tag="SOBRE A WEBFUN" title={<>Estratégia, design e código no mesmo projeto.</>} subtitle="A Webfun cria sites, lojas virtuais e sistemas sob medida, da definição da solução até a publicação." align="center" level="h1"/></div></div></section>
 <section className="v4-section v4-about-position"><div className="shell v4-about-position-grid v799-about-position-grid"><div className="v76-about-position-copy v799-about-position-copy"><span className="v4-tag v788-section-tag">Nossa posição</span><h2>O projeto começa <em>pelo que precisa resolver.</em></h2><p>Algumas empresas precisam de um site melhor. Outras precisam vender online, organizar reservas, criar uma área do cliente ou substituir processos manuais por um sistema.</p><p>Definimos o escopo a partir desse cenário e reunimos design, desenvolvimento e integrações no mesmo projeto.</p><Link href="/servicos" className="v4-secondary-button v799-about-position-cta">Conhecer os serviços <ArrowRight size={17}/></Link></div><figure className="v799-about-position-image"><Image src="/media/about/webfun-collaboration.webp" alt="Profissionais colaborando na definição de uma experiência digital" fill quality={92} sizes="(max-width: 900px) 100vw, 44vw"/></figure></div></section>
 <section className="v41-about-human"><div className="shell v41-about-human-grid"><div className="v41-about-human-image"><Image src="/media/human-v60/creative-collaboration.webp" alt="Profissionais revisando uma experiência digital em conjunto" fill sizes="(max-width: 900px) 100vw, 52vw"/><span>Focado em pessoas</span></div><div className="v41-about-human-copy"><span className="v4-tag v788-section-tag">Nossa visão</span><h2>Digital não é sobre tela. É sobre experiência.</h2><p>A interface é só o ponto de contato. O que importa é o que a pessoa consegue fazer com clareza, confiança e o mínimo de atrito possível.</p><div><b>Estratégia</b><b>Uso real</b><b>Resultado</b></div></div></div></section>
 <section className="v51-about-gallery"><div className="shell"><div className="v51-about-gallery-head"><span className="v4-tag v788-section-tag">No mundo real</span><h2>Projetamos para quem vai usar de verdade.</h2><p>Do primeiro contato ao uso cotidiano, buscamos diminuir atrito e aproximar tecnologia de situações reais — atendimento, compra, agendamento, gestão e relacionamento.</p></div><div className="v51-about-gallery-grid"><figure className="v51-about-gallery-main"><Image src="/media/human-v60/team-collaboration.webp" alt="Equipe discutindo decisões de interface e produto em um escritório" fill sizes="(max-width: 900px) 100vw, 68vw"/><figcaption><small>SERVIÇO + EXPERIÊNCIA</small><b>O digital precisa acompanhar o que acontece fora da tela.</b></figcaption></figure><figure className="v51-about-gallery-side"><Image src="/media/human-v60/mobile-planning.webp" alt="Profissional usando smartphone e planejamento em sua rotina de trabalho" fill sizes="(max-width: 900px) 100vw, 32vw"/><figcaption><small>USO COTIDIANO</small><b>Interfaces claras para decisões simples.</b></figcaption></figure></div></div></section>
 <section className="v714-founder"><div className="shell v714-founder-grid"><figure className="v714-founder-portrait"><Image src="/media/founder/felipe.webp" alt="Felipe, fundador da Webfun" fill sizes="(max-width: 900px) 100vw, 42vw"/><figcaption><strong>Felipe</strong><span>Fundador · Estratégia e direção</span></figcaption></figure><div className="v714-founder-copy"><span className="v4-tag v788-section-tag">Direção</span><h2>À frente da <em>Webfun.</em></h2><p>A Webfun é conduzida de perto, unindo visão de negócio, design e tecnologia em cada projeto. Da primeira conversa às decisões finais de interface e desenvolvimento, o objetivo é manter clareza, proximidade e responsabilidade em cada entrega.</p><p className="v714-founder-note">Mais do que colocar um site ou sistema no ar, a ideia é construir algo que faça sentido para o negócio e para quem vai usar.</p></div></div></section>
 <section className="v4-section v4-system-section"><div className="shell"><SectionIntro tag="COMO PENSAMOS" title={<>Do problema <em>à solução funcionando.</em></>} subtitle="Planejamento, interface e desenvolvimento seguem a mesma direção até a entrega."/><StudioSystem/></div></section>
 <section className="v4-section v4-principles"><div className="shell"><SectionIntro tag="PRINCÍPIOS" title={<>O que permanece quando o projeto muda.</>} subtitle="Segmento, escopo e tecnologia podem variar. Estes princípios continuam guiando as decisões."/><div className="v4-principles-grid">{principles.map(([title,text,Icon],i)=><article key={title}><div><Icon size={20}/></div><span>0{i+1}</span><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>
 <section className="v4-section v4-location"><div className="shell v4-location-grid"><div><span className="v4-tag v788-section-tag">De Canoinhas para o mundo</span><h2>Raiz local. <em>Projetos sem fronteira.</em></h2><p>A proximidade continua sendo um diferencial. A capacidade de colaborar, projetar e entregar não termina no mapa.</p><a href={whatsappHref('Olá, Webfun! Vi a página Sobre e quero conversar.')} target="_blank" rel="noreferrer" className="v4-primary-button">Falar com a Webfun</a></div><div className="v4-location-board"><div className="v4-map-lines"/><i/><div><small>BASE</small><b>Canoinhas — SC</b><span>Brasil</span></div></div></div></section>
 </main>}
