import Link from 'next/link';
import Image from 'next/image';
import { ArrowRight } from 'lucide-react';
import SectionIntro from '../../components/SectionIntro';
import ProcessExperience from '../../components/ProcessExperience';
import FAQ from '../../components/FAQ';
import ServiceIllustration from '../../components/ServiceIllustration';
import { services, whatsappHref } from '../../lib/data';

export const metadata={title:'Serviços',description:'Sites, lojas virtuais, sistemas, automações, UX/UI, SEO e performance pela Webfun.',alternates:{canonical:'/servicos'},openGraph:{title:'Serviços | Webfun',description:'Sites, lojas virtuais, sistemas, automações, UX/UI, SEO e performance pela Webfun.',url:'/servicos',type:'website',images:[{url:'/opengraph-image',width:1200,height:630,alt:'Webfun | Serviços'}]},twitter:{card:'summary_large_image',title:'Serviços | Webfun',description:'Sites, lojas virtuais, sistemas, automações, UX/UI, SEO e performance pela Webfun.',images:['/opengraph-image']}};

export default function ServicesPage(){return <main id="conteudo" className="v4-internal">
 <section className="v4-page-hero v4-services-hero"><div className="shell v80-page-hero-grid"><div className="v80-page-hero-copy"><SectionIntro tag="SERVIÇOS" title={<>Sites, lojas e sistemas para resolver o que trava.</>} subtitle="Escolhemos a solução de acordo com o objetivo: apresentar melhor, vender, organizar a operação ou automatizar processos." align="center" level="h1"/><div className="v4-service-filters" role="tablist" aria-label="Ir direto para um serviço">{services.map(s=><a key={s.slug} href={`#svc-${s.slug}`} role="tab">{s.title.split('&')[0].trim()}</a>)}</div></div></div></section>
 <section className="v4-section v4-services-catalog"><div className="shell"><div className="v4-service-list">{services.map(s=><Link href={`/servicos/${s.slug}`} id={`svc-${s.slug}`} className={`v4-service-row v4-theme-${s.theme}`} key={s.slug}><span>{s.number}</span><div><small>SERVIÇO</small><h2>{s.title}</h2><p>{s.short}</p></div><div className="v4-service-row-tags">{s.bullets.slice(0,3).map(x=><i key={x}>{x}</i>)}</div><figure className="v80-service-row-preview"><ServiceIllustration slug={s.slug}/></figure><b><ArrowRight size={18}/></b></Link>)}</div></div></section>
 <section className="v60-services-human"><div className="shell"><div className="v60-services-human-intro"><span className="v4-tag v788-section-tag">No mundo real</span><h2>Serviços digitais existem <em>para melhorar rotinas reais.</em></h2><p>Estratégia, interface e tecnologia só fazem sentido quando ajudam alguém a vender, atender, organizar, decidir ou trabalhar melhor.</p></div><div className="v60-services-human-grid"><figure className="v60-services-human-main"><Image src="/media/human-v60/laptop-professional.webp" alt="Profissional trabalhando em um notebook em escritório" fill sizes="(max-width: 900px) 100vw, 58vw"/><figcaption><small>PRESENÇA + PRODUTO</small><b>Tecnologia aplicada ao trabalho que precisa acontecer.</b></figcaption></figure><figure className="v60-services-human-side"><Image src="/media/human-v60/dashboard-professional.webp" alt="Profissional analisando indicadores em um dashboard" fill sizes="(max-width: 900px) 100vw, 42vw"/><figcaption><small>SISTEMAS + DADOS</small><b>Interfaces para transformar informação em decisão.</b></figcaption></figure></div></div></section>
 <section className="v4-section v4-process-section"><div className="shell"><SectionIntro tag="PROCESSO" title={<>Entender. Construir. <em>Publicar.</em></>} subtitle="Um processo claro para transformar necessidade em projeto funcionando."/><ProcessExperience/></div></section>
 <section className="v4-section v4-faq-section"><div className="shell v4-faq-grid"><SectionIntro tag="DÚVIDAS" title={<>Qual serviço faz sentido <em>para o seu cenário?</em></>} subtitle="Você não precisa decidir isso sozinho. A conversa pode começar pelo problema."/><FAQ/></div></section>
 <section className="v4-inline-cta"><div className="shell"><span className="v4-tag v788-section-tag">Conversa</span><h2>Não sabe exatamente <em>do que precisa?</em></h2><p>Conte o cenário. A gente ajuda a transformar isso em um escopo claro.</p><a href={whatsappHref('Olá, Webfun! Não sei exatamente qual serviço preciso, pode me ajudar?')} target="_blank" rel="noreferrer" className="v4-primary-button">Encontrar a solução ideal</a></div></section>
 </main>}
